version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    env_file:
      - deploy/conf.env
    ports:
      - 8000:8000
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 5d & wait $${!}; done;'"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - certbot
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped