version: '3.8'

services:
  redis:
    image: redis:5
    ports:
      - 6379:6379
    restart: unless-stopped

  db:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - deploy/conf.env
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    env_file:
      - deploy/conf.env
    ports:
      - 8000:8000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - db
      - redis
      - web
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  pgdata: