version: '3.8'

services:
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
    networks:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13.3
    depends_on:
      - redis
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - deploy/conf.env
    networks:
      - backend
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    env_file:
      - deploy/conf.env
    ports:
      - 8000:8000
    networks:
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 5d & wait $${!}; done;'"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - db
      - redis
      - web
      - certbot
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  backend: