version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    env_file:
      - deploy/conf.env
    ports:
      - 8000:8000
    restart: unless-stopped
