name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.DIRECTORY }}
            sudo git pull
            sudo docker tag alexfirechat_web:latest alexfirechat_web:old
            sudo docker build -t alexfirechat_web:latest .
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up --detach
            sudo docker image rm alexfirechat_web:old